const 
    jub = require('../index.js');
console.log('STYLE EXAMPLES:');
jub.log('Standart: '+'Hello World!', {style: 'standart'});
jub.log('Reset: '+'Hello World!', {style: 'reset'});
jub.log('Bold: '+'Hello World!', {style: 'bold'});
jub.log('Dim: '+'Hello World!', {style: 'dim'});
jub.log('Italic: '+'Hello World!', {style: 'italic'});
jub.log('Underline: '+'Hello World!', {style: 'underline'});
jub.log('Overline: '+'Hello World!', {style: 'overline'});
jub.log('Inverse: '+'Hello World!', {style: 'inverse'});
jub.log('Hidden: '+'Hello World!', {style: 'hidden'});
jub.log('Strikethrough: '+'Hello World!', {style: 'strikethrough'});
console.log('COLOR EXAMPLES:')
jub.log('Hello World!', {color: 'white'});
jub.log('Hello World!', {color: 'rgb(255,255,255)'});
jub.log('Hello World!', {color: '#FFFFFF'});
jub.log('Hello World!', {color: 'black'});
jub.log('Hello World!', {color: 'red'});
jub.log('Hello World!', {color: 'green'});
jub.log('Hello World!', {color: 'yellow'});
jub.log('Hello World!', {color: 'blue'});
jub.log('Hello World!', {color: 'magenta'});
jub.log('Hello World!', {color: 'gray'});
jub.log('Hello World!', {color: 'grey'});
jub.log('Hello World!', {color: 'brightBlack'});
jub.log('Hello World!', {color: 'brightWhite'});
jub.log('Hello World!', {color: 'brightRed'});
jub.log('Hello World!', {color: 'brightGreen'});
jub.log('Hello World!', {color: 'brightYellow'});
jub.log('Hello World!', {color: 'brightBlue'});
jub.log('Hello World!', {color: 'brightMagenta'});
jub.log('Hello World!', {color: 'brightCyan'});
console.log('BG EXAMPLES:')
jub.log('Hello World!', {bg: 'white'});
jub.log('Hello World!', {bg: 'rgb(255,255,255)'});
jub.log('Hello World!', {bg: '#FFFFFF'});
jub.log('Hello World!', {bg: 'black'});
jub.log('Hello World!', {bg: 'red'});
jub.log('Hello World!', {bg: 'green'});
jub.log('Hello World!', {bg: 'yellow'});
jub.log('Hello World!', {bg: 'blue'});
jub.log('Hello World!', {bg: 'magenta'});
jub.log('Hello World!', {bg: 'gray'});
jub.log('Hello World!', {bg: 'grey'});
jub.log('Hello World!', {bg: 'brightBlack'});
jub.log('Hello World!', {bg: 'brightWhite'});
jub.log('Hello World!', {bg: 'brightRed'});
jub.log('Hello World!', {bg: 'brightGreen'});
jub.log('Hello World!', {bg: 'brightYellow'});
jub.log('Hello World!', {bg: 'brightBlue'});
jub.log('Hello World!', {bg: 'brightMagenta'});
jub.log('Hello World!', {bg: 'brightCyan'});